version: '2.0'

services:
    nginx:
        image: cloud.canister.io:5000/jenshenrik/vestbirk-nginx:latest
        ports:
            - "81:81"
        depends_on:
            - api

    api:
        image: cloud.canister.io:5000/jenshenrik/vestbirk-api:latest
        environment:
            - VESTBIRK_ENVIRONMENT=development
            - VESTBIRK_DEBUG=TRUE
            - VESTBIRK_ALLOWED_HOSTS=api
        ports:
            - 8000:8000
