setup: &default
    docker:
        - image: circleci/python:3.6.1
    working_directory: ~/repo
    
version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build
    push_images:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run: 
                name: Login to TreeScale
                command: |
                    docker login --username $DOCKER_USER --password $DOCKER_PASSWORD cloud.canister.io:5000
            - run:
                name: Build and push images
                command: |
                    make build

                    docker tag vestbirk-api cloud.canister.io:5000/jenshenrik/vestbirk-api
                    docker push cloud.canister.io:5000/jenshenrik/vestbirk-api
            
                    docker tag vestbirk-nginx cloud.canister.io:5000/jenshenrik/vestbirk-nginx
                    docker push cloud.canister.io:5000/jenshenrik/vestbirk-nginx
    deploy:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "52:f3:eb:62:6b:f6:15:23:87:0a:1d:61:d6:b4:54:d8"
            - run:
                name: Deploy over SSH
                command: |
                    ssh $SSH_USER@$SSH_HOST "./deploy-vestbirk.sh"

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - push_images:
                requires:
                    - build
                filters:
                    branches:
                      only:
                        - master
            - deploy:
                requires:
                    - push_images
                filters:
                    branches:
                      only:
                        - master
