setup: &default
    docker:
        - image: circleci/python:3.6.1
    working_directory: ~/repo
    
version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build
    push_images:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run: 
                name: Login to TreeScale
                command: |
                    docker login --username $DOCKER_USER --password $DOCKER_PASSWORD cloud.canister.io:5000
            - run:
                name: Build and push images
                command: |
                    make build

                    docker tag vestbirk-api cloud.canister.io:5000/jenshenrik/vestbirk-api
                    docker push cloud.canister.io:5000/jenshenrik/vestbirk-api
            
                    docker tag vestbirk-nginx cloud.canister.io:5000/jenshenrik/vestbirk-nginx
                    docker push cloud.canister.io:5000/jenshenrik/vestbirk-nginx

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - push_images:
                requires:
                    - build
                      #filters:
                      #branches:
                      #only:
                      #- master
