setup: &default
    docker:
        - image: circleci/python:3.6.1
    working_directory: ~/repo
    
version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build
    push_images:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run: |
                docker login repo.treescale.com --username $DOCKER_USER --password $DOCKER_PASSWORD
                docker push repo.treescale.com/jenshenrik/vestbirk-backend:latest
            

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - push_images:
                requires:
                    - build
