setup: &default
    docker:
        - image: circleci/python:3.6.1
    working_directory: ~/repo
    
version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build
    push_images:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run: 
                name: Login to TreeScale
                command: |
                    docker login repo.treescale.com --username $DOCKER_USER --password $DOCKER_PASSWORD
            - run:
                name: Build and push images
                command: |
                    make build

                    docker tag vestbirk-nginx:latest repo.treescale.com/jenshenrik/vestbirk-nginx
                    docker push repo.treescale.com/jenshenrik/vestbirk-nginx
                    
                    docker tag vestbirk-api:latest repo.treescale.com/jenshenrik/vestbirk-api
                    docker push repo.treescale.com/jenshenrik/vestbirk-api
    deploy:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "a1:54:db:88:a7:1f:3e:d6:0d:93:05:a5:36:50:3c:cd"
            - run:
                name: Deploy over SSH
                command: |
                    ssh $SSH_USER@$SSH_HOST "./deploy-vestbirk.sh"
            

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - push_images:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
            - deploy:
                requires:
                    - push-images
